# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(kknn)
    library(parsnip)
    library(recipes)
    library(themis)
    library(workflows)
}
b <- board_folder(path = "pins-r")
v <- vetiver_pin_read(b, "final_knn_model", version = "20240702T224204Z-88d75")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
